language: php

php:
  - 5.3.3

before_script:
  - cp app/config/travis-parameters.yml app/config/parameters.yml
  - mysql -e 'create database myapp_test;'
  - php composer.phar self-update
  - composer install
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load

script: phpunit -c app --coverage-text
notifications:
  email:
    recipients:
      - yoan.roullard@gmail.com
      - q.hiss@hotmail.fr
      - clemgrim@gmail.com
    on_success: change
    on_failure: always