language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script: composer install

script: phpunit -c app
notifications:
  email:
    recipients:
      - yoan.roullard@gmail.com
      - q.hiss@hotmail.fr
      - clemgrim@gmail.com
    on_success: change
    on_failure: always